name: CI and CD

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install LibreOffice
      run: sudo apt-get install libreoffice-impress xmlstarlet poppler-utils
    - name: Build Extension
      run: make
    - name: Install Extension
      run: make install  
    - name: Test Extension
      run: make test


  cd:
    #if: github.event_name == 'push' && github.ref == 'master'

    needs: ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt-get install xmlstarlet
    - name: Build Extension
      run: make
    - name: Create GitHub Releases
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      with:
        tag_name: 0.8
        release_name: Release 0.8
        # Uncomment if some release notes are available
        #body: |
        #  Changes in this Release
        #  - First Change
        #  - Second Change
        draft: false
        prerelease: false
    - name: Post Extension to GitHub Releases
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/ExpandAnimations-0.8.oxt
        asset_name: ExpandAnimations-0.8.oxt
        asset_content_type: application/zip      
    - name: Increase Version
      run: ./increase-version.sh
    - name: Commit Git Changes 
      run: |
        git config --global user.email "versionbot@expandanimations.local"
        git config --global user.name "Version Bot"
        git add extension/description.xml
        git add .github/workflows/ci_and_cd.yml
        git commit -m "Extension version updated"
    - name: Push Git Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

          
