name: CI and CD

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install LibreOffice
      run: sudo apt-get install libreoffice-impress xmlstarlet poppler-utils
    - name: Build Extension
      run: make
    - name: Install Extension
      run: make install  
    - name: Test Extension
      run: make test


  cd:
    #if: github.event_name == 'push' && github.ref == 'master'

    needs: ci

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt-get install xmlstarlet
    - name: Build Extension
      run: make 
    - name: Generate Git Tag
      run: git tag ${VERSION}
      env:
        VERSION: $(xmlstarlet sel -N oo="http://openoffice.org/extensions/description/2006" -t -v "//oo:version/@value" extension/description.xml)
    - name: Create GitHub Releases
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        VERSION: $(xmlstarlet sel -N oo="http://openoffice.org/extensions/description/2006" -t -v "//oo:version/@value" extension/description.xml)
      with:
        tag_name: ${VERSION}
        release_name: Release ${VERSION}
        # Uncomment if some release notes are available
        #body: |
        #  Changes in this Release
        #  - First Change
        #  - Second Change
        draft: false
        prerelease: false
    - name: Post Extension to GitHub Releases
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: $(xmlstarlet sel -N oo="http://openoffice.org/extensions/description/2006" -t -v "//oo:version/@value" extension/description.xml)
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/ExpandAnimations-${VERSION}.oxt
        asset_name: ExpandAnimations-${VERSION}.oxt
        asset_content_type: application/zip      
    - name: Increase Version
      run: ./increase-version.sh
    - name: Commit Git Changes 
      run: |
        git add extension/description.xml
        git commit -m "Extension version updated"
        git push --all

          
